typography_spectrum: 0.9441127164755017
content_rating:
  adult: true
color:
  brandStrength: 0.9941059311386198
  lightness: 0.6846741642802954
  saturation: 0.7269217357970774
  rhythmicContrast: 0.437897976487875
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.6715851940680295
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0f7eade0-6bc6-4a9f-b094-416a979e390a.png
name: Beaux Motif
navigation:
  - name: Web Design
    url: beauxmotif.com
    type: external
title: Beautiful Artistic Design
description: Custom Interactive Websites
